### ISSUE TITLE
No module issue

### ISSUE THREAD

**Issue by leribe** [ex0dus-0x/dedsploit#1]
Hi Dedsploit, 
Thank you for your application, however, i'm getting below error on kali 2016.2 (64-bit), please help.

Traceback (most recent call last):
  File "/opt/dedsploit/dedsploit.py", line 4, in <module>
    from mainLib import *
  File "/opt/dedsploit/mainLib.py", line 13, in <module>
    import nmap, paramiko
ImportError: No module named nmap

**Comment by JonW27** [comment]
Did you use the installer script?

**Comment by leribe** [comment]
Hi Jonathan, 

yes, used the installation script and installed successfully.
 Kind Regards 
Tsepo Lesibe 

    On Wednesday, December 14, 2016 2:56 AM, Jonathan Wong <notifications@github.com> wrote:
 

 Did you use the installer script?—

**Comment by JonW27** [comment]
Hello Tsepo,

Looks like this was an issue on our part! You can delete the directory you just created and follow the README instructions again, or you can run this command:

`pip install python-nmap paramiko scapy terminaltables`

**Comment by ex0dus-0x** [comment]
I will be working on development this weekend. Once completed, execute a 

    git pull

in your terminal. Thanks for the issue!
